name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        volumes:
          - mongo-data:/data/db
        env:
          MONGO_INITDB_DATABASE: editor
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} # Your Docker Hub username
          password: ${{ secrets.DOCKER_HUB_TOKEN }}   # Your Docker Hub access token

      - name: Build and push Java image
        uses: docker/build-push-action@v3
        with:
          context: ./CollabCode/Dockerfiles/java
          file: Dockerfile
          push: true
          tags: your-dockerhub-username/java-container:latest

      - name: Build and push Python image
        uses: docker/build-push-action@v3
        with:
          context: ./CollabCode/Dockerfiles/python
          file: Dockerfile
          push: true
          tags: your-dockerhub-username/python-container:latest

      - name: Build and push Spring app image
        uses: docker/build-push-action@v3
        with:
          context: ./CollabCode
          push: true
          tags: your-dockerhub-username/spring-app:latest

      - name: Build and push React app image
        uses: docker/build-push-action@v3
        with:
          context: ./code-editor-frontend
          push: true
          tags: your-dockerhub-username/react-app:latest

      - name: Deploy to Server
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          ssh your_user@your_server_ip << 'ENDSSH'
            docker-compose -f /path/to/docker-compose.yml pull
            docker-compose -f /path/to/docker-compose.yml up -d
          ENDSSH

volumes:
  mongo-data:
